version: "3"

services:
  database:
    image: mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'dungeon'


  api:
    depends_on:
      - database
    build: .
    environment:
      MYSQL_URL: ''
    command: gunicorn -w 4 -b 0.0.0.0:8080 'main:create_app()'
    ports:
    - '8080:8080'