"""
    empty message
    Revision ID: ade36df3d94d
    Revises:
    Create Date: 2020-12-05 14:01:47.508334
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ade36df3d94d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'books',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'schools',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('book_id', sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'spells',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('casting_time', sa.String(length=256), nullable=False),
        sa.Column('components', sa.String(length=256), nullable=False),
        sa.Column('duration', sa.String(length=256), nullable=False),
        sa.Column('school_id', sa.String(length=36), nullable=False),
        sa.Column('range', sa.String(length=256), nullable=False),
        sa.Column('is_ritual', sa.Boolean(), nullable=False),
        sa.Column('book_id', sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
        sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spells')
    op.drop_table('schools')
    op.drop_table('books')
    # ### end Alembic commands ###
